sources:
  - name: perklysubscription
    handler:
      graphql:
        endpoint: https://api.studio.thegraph.com/query/92897/perklysubscription/version/latest
  - name: perklyVoucher
    handler:
      graphql:
        endpoint: https://api.studio.thegraph.com/query/92897/perklyvoucher/version/latest
documents:
  - ./graphql/GetDailySpendingsMerchant.gql
  - ./graphql/GetMerchantDashboardData.gql
  - ./graphql/GetMerchantSubscribers.gql
  - ./graphql/GetAirdropCompleteds.gql
