import { Poppins } from "next/font/google";
import "./globals.css";
import Navbar from "./Navbar";
import Providers from "./Providers";

const poppins = Poppins({
  style: ["normal", "italic"],
  display: "swap",
  subsets: ["latin"],
  weight: ["400", "500", "600", "700"],
});
export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body className={`${poppins.className} antialiased p-6`}>
        <Providers>
          <Navbar />
          {children}
        </Providers>
      </body>
    </html>
  );
}
