query GetAirdropCompleteds($merchantId: Bytes) {
  airdropCompleteds(
    orderBy: blockTimestamp
    first: 5
    orderDirection: desc
    where: { merchant: $merchantId }
  ) {
    merchant
    selectedRecipient
    blockTimestamp
  }
}
